name: Hello World Workflow

on: 
  push:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: arc-runner-set
    
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
